version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.3.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  userservice:
    build:
      context: ../ERPSystem/UserService
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - kafka
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  inventoryservice:
    build:
      context: ../ERPSystem/InventoryService
      dockerfile: Dockerfile
    ports:
      - "5001:80"
    depends_on:
      - kafka
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  orderservice:
    build:
      context: ../ERPSystem/OrderService
      dockerfile: Dockerfile
    ports:
      - "5002:80"
    depends_on:
      - kafka
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  frontend:
    build:
      context: ../erp-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - userservice
      - inventoryservice
      - orderservice
